### ISSUE TITLE
Handle Javascript in Markdown Files

### ISSUE THREAD

**Issue by hofbi** [latex4ei/tex4tum#24]
For the interactive content there is some JS in the markdown files. How should we handle this?

**Comment by elgor** [comment]
Maybe we could require that interactive diagrams / content is bundled into a separate markdown file that is included into the main article file

**Comment by hofbi** [comment]
We could also move the JS to a seperate .js file and include them. With this we get our markdown files "clean" from JS, so they are easy to read for most of the users. If there is somebody wants to contribute interactive content he has to step more into detail. With this we could introduce some parameters for including the JS to make some JS reuseable.

**Comment by elgor** [comment]
Clean from JS but we would still have html tags in the markdown file to access certain text spans by element. Furthermore we would separate the manipulated content from the manipulating logic which lowers the cohesion. I would suggest splitting according to content topic or static/interactive rather than by interpreter language.

**Comment by hofbi** [comment]
But putting the whole JS together could be helpful to create an object oriented structure as suggested in #9
